### ISSUE TITLE
0.4.0 release checklist

### ISSUE THREAD

**Issue by erikh** [erikh/saturn#40]
- [x] Fix notifications in google #19
- [x] #43
- [x] `sui` error handling #36 
- [x] Query Window configuration var #33 
- [x] DB corruption bug #37 
- [x] Update README's `sui` screenshot
- [x] #45
- [x] Fix memorydb duplication bug #42
- [x] #47
- [x] #51

**Comment by erikh** [comment]
I've removed attendance support for Google Calendar as a target feature. I think this would be better done in later releases.
